# Generated by Django 6.0.5 on 2026-05-14 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rechargetransaction',
            name='paystack_access_code',
            field=models.CharField(blank=True, help_text='Paystack access code for payment link', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rechargetransaction',
            name='paystack_auth_url',
            field=models.URLField(blank=True, help_text='Paystack authorization URL', null=True),
        ),
        migrations.AddField(
            model_name='rechargetransaction',
            name='paystack_reference',
            field=models.CharField(blank=True, help_text='Paystack payment reference', max_length=255, null=True),
        ),
    ]
