# Generated by Django 6.0.5 on 2026-05-15 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinvestment',
            name='transaction_reference',
            field=models.CharField(blank=True, help_text='Reference from ProductTransaction', max_length=64, null=True),
        ),
    ]
