# Generated by Django 6.0.5 on 2026-05-14 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_withdrawaltransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('term', models.CharField(blank=True, help_text='E.g. "10 days", "60 days", etc.', max_length=64)),
                ('daily_earnings', models.DecimalField(blank=True, decimal_places=2, help_text='Daily earnings for this product', max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_earnings', models.DecimalField(blank=True, decimal_places=2, help_text='Total earnings for the term', max_digits=12, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
    ]
