# Generated by Django 6.0.5 on 2026-05-15 02:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='producttransaction',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.product'),
        ),
        migrations.AddField(
            model_name='producttransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rechargetransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recharge_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='savedaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userbalance',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usercheckin',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checkin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userinvestment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='core.product'),
        ),
        migrations.AddField(
            model_name='userinvestment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usertask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.task'),
        ),
        migrations.AddField(
            model_name='usertask',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='withdrawaltransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='savedaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('account_type', 'mobile_money')), fields=('user', 'account_type', 'network', 'phone_number'), name='unique_mobile_money_account'),
        ),
        migrations.AddConstraint(
            model_name='savedaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('account_type', 'bank_transfer')), fields=('user', 'account_type', 'bank_name', 'account_number'), name='unique_bank_account'),
        ),
        migrations.AlterUniqueTogether(
            name='usertask',
            unique_together={('user', 'task')},
        ),
    ]
