# Generated by Django 6.0.5 on 2026-05-14 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iCare_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
