"""
Django settings for iCare project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
import dj_database_url
from pathlib import Path
import logging

logger = logging.getLogger(__name__)

from dotenv import load_dotenv

# Load environment variables from .env.paystack file
env_file = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))), '.env.paystack')
if os.path.exists(env_file):
    load_dotenv(env_file)
else:
    load_dotenv()  # Fall back to .env if .env.paystack doesn't exist


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

def get_env_var(var_name: str, default: str = None, required: bool = False) -> str:
    """Get environment variable with validation"""
    value = os.environ.get(var_name, default)
    if required and not value:
        raise ValueError(f"Environment variable {var_name} is required but not set")
    return value

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = get_env_var("SECRET_KEY", required=True)


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False").lower() == "true"

ALLOWED_HOSTS = [host.strip() for host in os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1,[::1],robororxs.onrender.com,roboforxs.vercel.app').split(',')]
# ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "").split(",")
CSRF_TRUSTED_ORIGINS = [
    "https://b2a9-154-161-153-208.ngrok-free.app",
    'https://robororxs.onrender.com',
    'https://roboforxs.vercel.app'
]
CSRF_TRUSTED_ORIGINS = os.environ.get('CSRF_TRUSTED_ORIGINS', 'http://localhost').split(' ')

SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = False
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'
CLOUDINARY_SECURE = True

SESSION_COOKIE_AGE = 900  # 900 seconds = 15 minutes
SESSION_EXPIRE_AT_BROWSER_CLOSE = True # Log user out when browser is closed (optional but recommended)
SESSION_SAVE_EVERY_REQUEST = True # Refresh session expiration on each request (to detect activity)


if not DEBUG:
    # SSL Settings (controlled by Render env var)
    enable_ssl = os.getenv('ENABLE_SSL_SECURITY', 'False').lower() == 'true'
    if enable_ssl:
        SESSION_COOKIE_SECURE = True
        CSRF_COOKIE_SECURE = True
        SECURE_SSL_REDIRECT = True
        SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '31536000'))
        SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    
    # Safe security headers (always enable in production)
    SECURE_BROWSER_XSS_FILTER = os.getenv('SECURE_BROWSER_XSS_FILTER', 'True').lower() == 'true'
    SECURE_CONTENT_TYPE_NOSNIFF = os.getenv('SECURE_CONTENT_TYPE_NOSNIFF', 'True').lower() == 'true'
    X_FRAME_OPTIONS = os.getenv('X_FRAME_OPTIONS', 'DENY')
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',

    # My apps
    'iCare_auth',
    'core',
    'phonenumber_field',
    'tailwind',
    'theme',

    'pwa',
    'webpush',
    'celery',
    'django_extensions',
]

TAILWIND_APP_NAME = "theme"
NPM_BIN_PATH = 'npm.cmd'

# Tell Django how to interpret regional phone numbers (if users don't include country code)
PHONENUMBER_DEFAULT_REGION = 'GH'  # GH = Ghana, since your users have +233 numbers

# How phone numbers are stored in the database
PHONENUMBER_DB_FORMAT = 'E164'  # Stores as +233XXXXXXXXX format (recommended)

# Default format for displaying numbers
PHONENUMBER_DEFAULT_FORMAT = 'INTERNATIONAL'  # Shows as +233 XX XXX XXXX


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'iCare.urls'

AUTH_USER_MODEL = 'iCare_auth.User'  # Use our custom user model
LOGIN_REDIRECT_URL = 'login'  # Redirect to login page after successful registration
LOGIN_URL = 'login'
LOGOUT_REDIRECT_URL = 'login'  # Redirect to login page after logout

AUTHENTICATION_BACKENDS = [
    'iCare_auth.backends.PhoneNumberBackend',
    'django.contrib.auth.backends.ModelBackend',  # Keep default for admin access
]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],  # Global templates directory
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'iCare.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
# if DEBUG:
#     DATABASES = {
#         'default': {
#             'ENGINE': 'django.db.backends.sqlite3',
#             'NAME': BASE_DIR / 'db.sqlite3',
#         }
#     }
# else:
#     DATABASES = {
#         'default': dj_database_url.config(
#             default=os.getenv("DATABASE_URL"),
#             conn_max_age=0 if os.getenv("VERCEL") else 600,
#             ssl_require=True,
#         )
#     }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
if not DEBUG:
    STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles_build')
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


PAYSTACK_PUBLIC_KEY = os.getenv('PAYSTACK_PUBLIC_KEY', '')
PAYSTACK_SECRET_KEY = os.getenv('PAYSTACK_SECRET_KEY', '')
PAYSTACK_CALLBACK_URL = os.getenv('PAYSTACK_CALLBACK_URL', 'http://localhost:8000/payment/callback/')
PAYSTACK_WEBHOOK_URL = os.getenv('PAYSTACK_WEBHOOK_URL', 'http://localhost:8000/payment/webhook/')


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.zoho.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL =  os.getenv('DEFAULT_FROM_EMAIL')



# Celery Configuration
CELERY_BROKER_URL = os.getenv('REDIS_URL', 'redis://localhost:6379/0')  # Redis as message broker
CELERY_RESULT_BACKEND = os.getenv('REDIS_URL', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# Robustness settings for Redis/Celery
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_BROKER_TRANSPORT_OPTIONS = {
    'max_retries': 5,
    'interval_start': 0,
    'interval_step': 0.2,
    'interval_max': 0.5,
    'visibility_timeout': 3600,
}
CELERY_REDIS_RETRY_ON_TIMEOUT = True

# PWA Configuration
PWA_APP_NAME = 'RoBoForxs'
PWA_APP_DESCRIPTION = "Professional Trading Platform - Fast, Secure, Reliable"
PWA_APP_THEME_COLOR = '#2563eb'
PWA_APP_BACKGROUND_COLOR = '#f8fafc'
PWA_APP_DISPLAY = 'standalone'
PWA_APP_SCOPE = '/'
PWA_APP_START_URL = '/'
PWA_APP_ORIENTATION = 'portrait-primary'
PWA_APP_STATUS_BAR_COLOR = '#2563eb'

# PWA Icons using your RoboForxs Logo
PWA_APP_ICONS = [
    {
        'src': '/static/imgs/icons/icon-72x72.png',
        'sizes': '72x72',
        'type': 'image/png',
        'purpose': 'any maskable'
    },
    {
        'src': '/static/imgs/icons/icon-96x96.png',
        'sizes': '96x96',
        'type': 'image/png'
    },
    {
        'src': '/static/imgs/icons/icon-128x128.png',
        'sizes': '128x128',
        'type': 'image/png'
    },
    {
        'src': '/static/imgs/icons/icon-144x144.png',
        'sizes': '144x144',
        'type': 'image/png'
    },
    {
        'src': '/static/imgs/icons/icon-152x152.png',
        'sizes': '152x152',
        'type': 'image/png'
    },
    {
        'src': '/static/imgs/icons/icon-192x192.png',
        'sizes': '192x192',
        'type': 'image/png',
        'purpose': 'any maskable'
    },
    {
        'src': '/static/imgs/icons/icon-384x384.png',
        'sizes': '384x384',
        'type': 'image/png'
    },
    {
        'src': '/static/imgs/icons/icon-512x512.png',
        'sizes': '512x512',
        'type': 'image/png',
        'purpose': 'any maskable'
    }
]

# Apple Touch Icons
PWA_APP_ICONS_APPLE = [
    {
        'src': '/static/imgs/icons/icon-152x152.png',
        'sizes': '152x152',
        'type': 'image/png'
    },
    {
        'src': '/static/imgs/icons/icon-167x167.png',
        'sizes': '167x167',
        'type': 'image/png'
    },
    {
        'src': '/static/imgs/icons/icon-180x180.png',
        'sizes': '180x180',
        'type': 'image/png'
    }
]

# Splash screens (iOS)
PWA_APP_SPLASH_SCREEN = [
    {
        'src': '/static/imgs/icons/splash-640x1136.png',
        'media': '(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2)',
        'sizes': '640x1136'
    },
    {
        'src': '/static/imgs/icons/splash-750x1334.png',
        'media': '(device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2)',
        'sizes': '750x1334'
    },
    {
        'src': '/static/imgs/icons/splash-1242x2208.png',
        'media': '(device-width: 414px) and (device-height: 736px) and (-webkit-device-pixel-ratio: 3)',
        'sizes': '1242x2208'
    },
    {
        'src': '/static/imgs/icons/splash-1125x2436.png',
        'media': '(device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3)',
        'sizes': '1125x2436'
    },
    {
        'src': '/static/imgs/icons/splash-1536x2048.png',
        'media': '(device-width: 768px) and (device-height: 1024px) and (-webkit-device-pixel-ratio: 2)',
        'sizes': '1536x2048'
    }
]

# Shortcuts
PWA_APP_SHORTCUTS = [
    {
        'name': 'Home',
        'url': '/core/home/',
        'description': 'Go to home page',
        'icons': [{'src': '/static/imgs/icons/icon-96x96.png', 'sizes': '96x96'}]
    },
    {
        'name': 'Profile',
        'url': '/profile/',
        'description': 'View your profile',
        'icons': [{'src': '/static/imgs/icons/icon-96x96.png', 'sizes': '96x96'}]
    },
    {
        'name': 'Recharge',
        'url': '/core/recharge/',
        'description': 'Add funds',
        'icons': [{'src': '/static/imgs/icons/icon-96x96.png', 'sizes': '96x96'}]
    },
    {
        'name': 'Withdraw',
        'url': '/core/withdraw/',
        'description': 'Withdraw funds',
        'icons': [{'src': '/static/imgs/icons/icon-96x96.png', 'sizes': '96x96'}]
    }
]

PWA_APP_DIR = 'ltr'
PWA_APP_LANG = 'en-US'
PWA_SERVICE_WORKER_PATH = os.path.join(BASE_DIR, 'static/js/serviceworker.js')


WEBPUSH_SETTINGS = {
    "VAPID_PUBLIC_KEY": "BKMiOCLDwcRSsdzAwC5Apbyu0w-awHFKNyH3B8VJhQkOwT_tze0LubhfvuSw4BCAHPtZXA9tAHXcCZ1fhv0auFk",
    "VAPID_PRIVATE_KEY": "MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgiZBOtFtaJJEEBBBNLeBWmAorFFD9ETbFYLUBBYIqEkyhRANCAASjIjgiw8HEUrHcwMAuQKW8rtMPmsBxSjch9wfFSYUJDsE_7c3tC7m4X77ksOAQgBz7WVwPbQB13AmdX4b9GrhZ",
    "VAPID_ADMIN_EMAIL": "mailto:essetech3@gmail.com"  # Change to your email
}


REDIS_URL = os.getenv('REDIS_URL')
if REDIS_URL:
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": REDIS_URL,
            "OPTIONS": {
                # "CLIENT_CLASS": "django_redis.client.DefaultClient",
                "IGNORE_EXCEPTIONS": True,
                "SOCKET_CONNECT_TIMEOUT": 5,  # seconds
                "SOCKET_TIMEOUT": 5,  # seconds
                "CONNECTION_POOL_KWARGS": {
                    "max_connections": 8,  # Free Redis has 10 max connections
                    "retry_on_timeout": True,
                }
            }
        }
    }
    
    SESSION_ENGINE = "django.contrib.sessions.backends.cache"
    SESSION_CACHE_ALIAS = "default"
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        }
    }
    SESSION_ENGINE = "django.contrib.sessions.backends.db"


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,

    'formatters': {
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },

    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },

    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },

    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.security': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'asgiref.sync': {
            'handlers': ['console'],
            'level': 'CRITICAL',
            'propagate': False,
        },
    },
}


