"""
Django settings for iCare project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Load environment variables from .env.paystack file
env_file = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))), '.env.paystack')
if os.path.exists(env_file):
    load_dotenv(env_file)
else:
    load_dotenv()  # Fall back to .env if .env.paystack doesn't exist


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-o!6+@9%e-ya5au37%lg&wr-vyz7!u=%(41xq)99v)w5*zw6hfp'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    ".ngrok-free.app",
]
# ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "").split(",")
CSRF_TRUSTED_ORIGINS = [
    "https://649d-154-161-8-99.ngrok-free.app",
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',

    # My apps
    'iCare_auth',
    'core',
    'phonenumber_field',
    'tailwind',
    'theme',

    'pwa',
]

TAILWIND_APP_NAME = "theme"
NPM_BIN_PATH = 'npm.cmd'

# Tell Django how to interpret regional phone numbers (if users don't include country code)
PHONENUMBER_DEFAULT_REGION = 'GH'  # GH = Ghana, since your users have +233 numbers

# How phone numbers are stored in the database
PHONENUMBER_DB_FORMAT = 'E164'  # Stores as +233XXXXXXXXX format (recommended)

# Default format for displaying numbers
PHONENUMBER_DEFAULT_FORMAT = 'INTERNATIONAL'  # Shows as +233 XX XXX XXXX


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'iCare.urls'

AUTH_USER_MODEL = 'iCare_auth.User'  # Use our custom user model
LOGIN_REDIRECT_URL = 'login'  # Redirect to login page after successful registration
LOGIN_URL = 'login'
LOGOUT_REDIRECT_URL = 'login'  # Redirect to login page after logout

AUTHENTICATION_BACKENDS = [
    'iCare_auth.backends.PhoneNumberBackend',
    'django.contrib.auth.backends.ModelBackend',  # Keep default for admin access
]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],  # Global templates directory
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'iCare.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


PAYSTACK_PUBLIC_KEY = os.getenv('PAYSTACK_PUBLIC_KEY', '')
PAYSTACK_SECRET_KEY = os.getenv('PAYSTACK_SECRET_KEY', '')
PAYSTACK_CALLBACK_URL = os.getenv('PAYSTACK_CALLBACK_URL', 'http://localhost:8000/payment/callback/')
PAYSTACK_WEBHOOK_URL = os.getenv('PAYSTACK_WEBHOOK_URL', 'http://localhost:8000/payment/webhook/')


# Celery Configuration
CELERY_BROKER_URL = 'redis://localhost:6379/0'  # Redis as message broker
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'


# PWA Configuration
PWA_APP_NAME = 'RoBosForx'
PWA_APP_DESCRIPTION = "Professional Trading Platform - Fast, Secure, Reliable"
PWA_APP_THEME_COLOR = '#2563eb'  # Blue-600 to match your theme
PWA_APP_BACKGROUND_COLOR = '#f8fafc'  # Slate-50
PWA_APP_DISPLAY = 'standalone'
PWA_APP_SCOPE = '/'
PWA_APP_ORIENTATION = 'portrait-primary'
PWA_APP_START_URL = '/dashboard/'  # Changed to dashboard for better UX
PWA_APP_STATUS_BAR_COLOR = '#2563eb'  # Changed from 'default' to match theme

# Updated icons with proper sizes
PWA_APP_ICONS = [
    {
        'src': '/static/images/icons/icon-72x72.png',
        'sizes': '72x72',
        'type': 'image/png',
        'purpose': 'any maskable'
    },
    {
        'src': '/static/images/icons/icon-96x96.png',
        'sizes': '96x96',
        'type': 'image/png'
    },
    {
        'src': '/static/images/icons/icon-128x128.png',
        'sizes': '128x128',
        'type': 'image/png'
    },
    {
        'src': '/static/images/icons/icon-144x144.png',
        'sizes': '144x144',
        'type': 'image/png'
    },
    {
        'src': '/static/images/icons/icon-152x152.png',
        'sizes': '152x152',
        'type': 'image/png'
    },
    {
        'src': '/static/images/icons/icon-192x192.png',
        'sizes': '192x192',
        'type': 'image/png'
    },
    {
        'src': '/static/images/icons/icon-384x384.png',
        'sizes': '384x384',
        'type': 'image/png'
    },
    {
        'src': '/static/images/icons/icon-512x512.png',
        'sizes': '512x512',
        'type': 'image/png',
        'purpose': 'any maskable'
    }
]

PWA_APP_ICONS_APPLE = [
    {
        'src': '/static/images/icons/icon-152x152.png',
        'sizes': '152x152',
        'type': 'image/png'
    },
    {
        'src': '/static/images/icons/icon-167x167.png',
        'sizes': '167x167',
        'type': 'image/png'
    },
    {
        'src': '/static/images/icons/icon-180x180.png',
        'sizes': '180x180',
        'type': 'image/png'
    }
]

# Splash screens for iOS devices
PWA_APP_SPLASH_SCREEN = [
    {
        'src': '/static/images/icons/splash-640x1136.png',
        'media': '(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2)',
        'sizes': '640x1136'
    },
    {
        'src': '/static/images/icons/splash-750x1334.png',
        'media': '(device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2)',
        'sizes': '750x1334'
    },
    {
        'src': '/static/images/icons/splash-1242x2208.png',
        'media': '(device-width: 414px) and (device-height: 736px) and (-webkit-device-pixel-ratio: 3)',
        'sizes': '1242x2208'
    },
    {
        'src': '/static/images/icons/splash-1125x2436.png',
        'media': '(device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3)',
        'sizes': '1125x2436'
    },
    {
        'src': '/static/images/icons/splash-1536x2048.png',
        'media': '(device-width: 768px) and (device-height: 1024px) and (-webkit-device-pixel-ratio: 2)',
        'sizes': '1536x2048'
    }
]

PWA_APP_DIR = 'ltr'
PWA_APP_LANG = 'en-US'

# Updated shortcuts relevant to trading app
PWA_APP_SHORTCUTS = [
    {
        'name': 'Dashboard',
        'url': '/dashboard/',
        'description': 'View your trading dashboard',
        'icons': [{'src': '/static/images/icons/icon-96x96.png', 'sizes': '96x96'}]
    },
    {
        'name': 'Trade',
        'url': '/trade/',
        'description': 'Start trading',
        'icons': [{'src': '/static/images/icons/icon-96x96.png', 'sizes': '96x96'}]
    },
    {
        'name': 'Top Up',
        'url': '/topup/',
        'description': 'Add funds to your account',
        'icons': [{'src': '/static/images/icons/icon-96x96.png', 'sizes': '96x96'}]
    },
    {
        'name': 'Withdraw',
        'url': '/withdraw/',
        'description': 'Withdraw your earnings',
        'icons': [{'src': '/static/images/icons/icon-96x96.png', 'sizes': '96x96'}]
    }
]

PWA_APP_SCREENSHOTS = [
    {
        'src': '/static/images/screenshots/dashboard.jpg',
        'sizes': '1280x720',
        'type': 'image/jpeg',
        'form_factor': 'wide',
        'label': 'Trading Dashboard'
    },
    {
        'src': '/static/images/screenshots/trading.jpg',
        'sizes': '1280x720',
        'type': 'image/jpeg',
        'form_factor': 'wide',
        'label': 'Trading Interface'
    },
    {
        'src': '/static/images/screenshots/mobile.jpg',
        'sizes': '750x1334',
        'type': 'image/jpeg',
        'form_factor': 'narrow',
        'label': 'Mobile Trading View'
    }
]

# Enhanced service worker path
PWA_SERVICE_WORKER_PATH = os.path.join(BASE_DIR, 'static/js/serviceworker.js')